export const PRODUCTS = [
    {
        id: 1,
        name: 'Cotton T-Shirt',
        description: 'Comfortable and breathable cotton t-shirt for casual wear.',
        price: '$15.99',
        addedOn: '2024-05-03',
        category: 'T-Shirts',
        fabric: 'Cotton',
        occasion: 'Casual',
        idealFor: 'Men',
        suitableFor: ['Daily Wear', 'Outdoor Activities'],
        raw_materials: ['100% Cotton'],
        pattern: 'Solid',
        work: 'Plain',
        segment: 'Men\'s Clothing'
    },
    {
        id: 2,
        name: 'Silk Dress',
        description: 'Elegant silk dress suitable for formal events and parties.',
        price: '$99.99',
        addedOn: '2024-05-03',
        category: 'Dresses',
        fabric: 'Silk',
        occasion: 'Formal',
        idealFor: 'Women',
        suitableFor: ['Parties', 'Weddings'],
        raw_materials: ['100% Silk'],
        pattern: 'Floral',
        work: 'Embroidered',
        segment: 'Women\'s Clothing'
    },
    {
        id: 3,
        name: 'Denim Jeans',
        description: 'Classic denim jeans for everyday wear.',
        price: '$49.99',
        addedOn: '2024-05-03',
        category: 'Jeans',
        fabric: 'Denim',
        occasion: 'Casual',
        idealFor: 'Unisex',
        suitableFor: ['Daily Wear', 'Casual Outings'],
        raw_materials: ['Denim'],
        pattern: 'Plain',
        work: 'Stitched',
        segment: 'Unisex Clothing'
    },
    {
        id: 4,
        name: 'Linen Shirt',
        description: 'Lightweight and breathable linen shirt perfect for summer days.',
        price: '$29.99',
        addedOn: '2024-05-03',
        category: 'Shirts',
        fabric: 'Linen',
        occasion: 'Casual',
        idealFor: 'Men',
        suitableFor: ['Beach Outings', 'Casual Gatherings'],
        raw_materials: ['Linen'],
        pattern: 'Striped',
        work: 'Plain',
        segment: 'Men\'s Clothing'
    },
    {
        id: 5,
        name: 'Wool Sweater',
        description: 'Cozy wool sweater to keep you warm in chilly weather.',
        price: '$59.99',
        addedOn: '2024-05-03',
        category: 'Sweaters',
        fabric: 'Wool',
        occasion: 'Winter',
        idealFor: 'Unisex',
        suitableFor: ['Cold Weather', 'Outdoor Activities'],
        raw_materials: ['Wool'],
        pattern: 'Knitted',
        work: 'Plain',
        segment: 'Unisex Clothing'
    },
    {
        id: 6,
        name: 'Polyester Blouse',
        description: 'Stylish polyester blouse for office and formal occasions.',
        price: '$39.99',
        addedOn: '2024-05-03',
        category: 'Blouses',
        fabric: 'Polyester',
        occasion: 'Formal',
        idealFor: 'Women',
        suitableFor: ['Office Wear', 'Business Meetings'],
        raw_materials: ['Polyester'],
        pattern: 'Checked',
        work: 'Printed',
        segment: 'Women\'s Clothing'
    },
    {
        id: 7,
        name: 'Leather Jacket',
        description: 'Trendy leather jacket for a rugged and stylish look.',
        price: '$129.99',
        addedOn: '2024-05-03',
        category: 'Jackets',
        fabric: 'Leather',
        occasion: 'Casual',
        idealFor: 'Men',
        suitableFor: ['Biker Outfits', 'Night Outs'],
        raw_materials: ['Leather'],
        pattern: 'Solid',
        work: 'Stitched',
        segment: 'Men\'s Clothing'
    },
    {
        id: 8,
        name: 'Chiffon Scarf',
        description: 'Light and airy chiffon scarf to add a touch of elegance to your outfit.',
        price: '$19.99',
        addedOn: '2024-05-03',
        category: 'Scarves',
        fabric: 'Chiffon',
        occasion: 'Casual',
        idealFor: 'Women',
        suitableFor: ['Day Outings', 'Summer Evenings'],
        raw_materials: ['Chiffon'],
        pattern: 'Printed',
        work: 'Plain',
        segment: 'Women\'s Accessories'
    },
    {
        id: 9,
        name: 'Velvet Blazer',
        description: 'Luxurious velvet blazer for a sophisticated and classy look.',
        price: '$149.99',
        addedOn: '2024-05-03',
        category: 'Blazers',
        fabric: 'Velvet',
        occasion: 'Formal',
        idealFor: 'Men',
        suitableFor: ['Evening Events', 'Dinner Parties'],
        raw_materials: ['Velvet'],
        pattern: 'Solid',
        work: 'Embroidered',
        segment: 'Men\'s Clothing'
    },
    {
        id: 10,
        name: 'Satin Pajamas',
        description: 'Soft and silky satin pajamas for a comfortable night\'s sleep.',
        price: '$34.99',
        addedOn: '2024-05-03',
        category: 'Pajamas',
        fabric: 'Satin',
        occasion: 'Nightwear',
        idealFor: 'Unisex',
        suitableFor: ['Sleeping', 'Lounging'],
        raw_materials: ['Satin'],
        pattern: 'Plain',
        work: 'Plain',
        segment: 'Unisex Clothing'
    },
    {
        id: 11,
        name: 'Cashmere Scarf',
        description: 'Warm and luxurious cashmere scarf for cold winter days.',
        price: '$79.99',
        addedOn: '2024-05-03',
        category: 'Scarves',
        fabric: 'Cashmere',
        occasion: 'Winter',
        idealFor: 'Unisex',
        suitableFor: ['Cold Weather', 'Outdoor Activities'],
        raw_materials: ['Cashmere'],
        pattern: 'Solid',
        work: 'Plain',
        segment: 'Unisex Accessories'
    },
    {
        id: 12,
        name: 'Lace Dress',
        description: 'Elegant lace dress for special occasions and evening events.',
        price: '$69.99',
        addedOn: '2024-05-03',
        category: 'Dresses',
        fabric: 'Lace',
        occasion: 'Formal',
        idealFor: 'Women',
        suitableFor: ['Parties', 'Dinners'],
        raw_materials: ['Lace'],
        pattern: 'Floral',
        work: 'Embroid'
    }
]
